// SERVICE CALLS
export const SERVICE_BEGIN_CALL = "SERVICE BEGIN CALL";
export const SERVICE_CALL_ERROR = "SERVICE CALL ERROR";
// SOCIAL INTERACTIONS
export const SOCIAL_INTERACTIONS_LOAD_SUCCESS = "SOCIAL INTERACTIONS LOAD SUCCESS";
export const SOCIAL_INTERACTIONS_LOAD_RECENT_SUCCESS = "SOCIAL INTERACTIONS LOAD RECENT SUCCESS";
export const SOCIAL_INTERACTIONS_LOAD_GROUP_SUCCESS = "SOCIAL INTERACTIONS LOAD GROUP SUCCESS";
export const SOCIAL_INTERACTION_CREATE_SUCCESS = "SOCIAL INTERACTION CREATE SUCCESS";
export const SOCIAL_INTERACTION_UPDATE_SUCCESS = "SOCIAL INTERACTION UPDATE SUCCESS";
export const SOCIAL_INTERACTION_DELETE_SUCCESS = "SOCIAL INTERACTION DELETE SUCCESS";
export const SOCIAL_INTERACTION_CHECK_DISTANCING = "SOCIAL INTERACTION CHECK DISTANCING";
export const SOCIAL_INTERACTION_GET_DISTINCT = "SOCIAL INTERACTION GET DISTINCT";
// VISITED PLACES
export const VISITED_PLACES_LOAD_SUCCESS = "VISITED PLACES LOAD SUCCESS";
export const VISITED_PLACES_LOAD_RECENT_SUCCESS = "VISITED PLACES LOAD RECENT SUCCESS";
export const VISITED_PLACES_LOAD_GROUP_SUCCESS = "VISITED PLACES LOAD GROUP SUCCESS";
export const VISITED_PLACE_CREATE_SUCCESS = "VISITED PLACE CREATE SUCCESS";
export const VISITED_PLACE_UPDATE_SUCCESS = "VISITED PLACE UPDATE SUCCESS";
export const VISITED_PLACE_DELETE_SUCCESS = "VISITED PLACE DELETE SUCCESS";
export const VISITED_PLACE_CHECK_CROWDED = "VISITED PLACE CHECK IF CROWDED";
export const VISITED_PLACE_GET_DISTINCT = "VISITED PLACE GET DISTINCT";
